apiVersion: v1
kind: Service
metadata:
 name: marco
 labels:
   app: marco
spec:
 ports:
 - port: 5434
   name: db
 type: ClusterIP  
 selector:
   app: marco
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: marco
spec:
 selector:
   matchLabels:
     app: marco
 replicas: 1
 serviceName: marco
 template:
   metadata:
     labels:
       app: marco
   spec:
     terminationGracePeriodSeconds: 10
     containers:
     - name: marco
       image: postgres:14
       imagePullPolicy: "IfNotPresent"
       ports:
       - containerPort: 5434
         name: db
       env:
       - name: PGDATA
         value: /data/pgdata
       envFrom:
       - configMapRef:
           name: postgres-config
       volumeMounts:
       - name: db
         mountPath: /data
 volumeClaimTemplates:
 - metadata:
     name: db
   spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 1Gi
